title: "CSE194: Hacker History"
description: "The Spring 2025 session of CSE194: Hacker History"
markdown: kramdown
future: true

collections:
  profiles:
    output: true
    permalink: /profiles/:title/
